
package b4j.docU;

import anywheresoftware.b4a.pc.PCBA;
import anywheresoftware.b4a.pc.RemoteObject;

public class jamtableclvcamposbuilder {
    public static RemoteObject myClass;
	public jamtableclvcamposbuilder() {
	}
    public static PCBA staticBA = new PCBA(null, jamtableclvcamposbuilder.class);

public static RemoteObject __c = RemoteObject.declareNull("anywheresoftware.b4a.keywords.Common");
public static RemoteObject _version = RemoteObject.createImmutable(0f);
public static RemoteObject _fx = RemoteObject.declareNull("anywheresoftware.b4j.objects.JFX");
public static RemoteObject _frm = RemoteObject.declareNull("anywheresoftware.b4j.objects.Form");
public static RemoteObject _clvlistacampos = RemoteObject.declareNull("b4j.example.customlistview");
public static RemoteObject _dialog = RemoteObject.declareNull("b4j.docU.b4xdialog");
public static RemoteObject _xui = RemoteObject.declareNull("anywheresoftware.b4a.objects.B4XViewWrapper.XUI");
public static RemoteObject _dragger = RemoteObject.declareNull("b4j.docU.jamtableclvclvdragger");
public static RemoteObject _filechooser = RemoteObject.declareNull("anywheresoftware.b4j.objects.FileChooserWrapper");
public static RemoteObject _currentfile = RemoteObject.createImmutable("");
public static RemoteObject _currentfilestring = RemoteObject.createImmutable("");
public static RemoteObject _menubar1 = RemoteObject.declareNull("anywheresoftware.b4j.objects.MenuItemWrapper.MenuBarWrapper");
public static RemoteObject _cmbtheme = RemoteObject.declareNull("anywheresoftware.b4j.objects.ComboBoxWrapper");
public static RemoteObject _txtid = RemoteObject.declareNull("anywheresoftware.b4j.objects.TextInputControlWrapper.TextFieldWrapper");
public static RemoteObject _cbocampo = RemoteObject.declareNull("anywheresoftware.b4j.objects.ComboBoxWrapper");
public static RemoteObject _txtaliascampo = RemoteObject.declareNull("anywheresoftware.b4j.objects.TextInputControlWrapper.TextFieldWrapper");
public static RemoteObject _cbotipodato = RemoteObject.declareNull("anywheresoftware.b4j.objects.ComboBoxWrapper");
public static RemoteObject _chkboxesfecha = RemoteObject.declareNull("anywheresoftware.b4j.objects.CheckboxWrapper");
public static RemoteObject _chkboxcampocalculado = RemoteObject.declareNull("anywheresoftware.b4j.objects.CheckboxWrapper");
public static RemoteObject _cbotipocontrolfiltro = RemoteObject.declareNull("anywheresoftware.b4j.objects.ComboBoxWrapper");
public static RemoteObject _chkboxkeyid = RemoteObject.declareNull("anywheresoftware.b4j.objects.CheckboxWrapper");
public static RemoteObject _lblordenkeyid = RemoteObject.declareNull("anywheresoftware.b4j.objects.LabelWrapper");
public static RemoteObject _chkboxnonulo = RemoteObject.declareNull("anywheresoftware.b4j.objects.CheckboxWrapper");
public static RemoteObject _chkboxconvalordefecto = RemoteObject.declareNull("anywheresoftware.b4j.objects.CheckboxWrapper");
public static RemoteObject _txtvalordefecto = RemoteObject.declareNull("anywheresoftware.b4j.objects.TextInputControlWrapper.TextFieldWrapper");
public static RemoteObject _chkboxesbooleano = RemoteObject.declareNull("anywheresoftware.b4j.objects.CheckboxWrapper");
public static RemoteObject _txtvalortruecampobooleano = RemoteObject.declareNull("anywheresoftware.b4j.objects.TextInputControlWrapper.TextFieldWrapper");
public static RemoteObject _tipocontrolfiltro_textfield = RemoteObject.createImmutable("");
public static RemoteObject _tipocontrolfiltro_combobox = RemoteObject.createImmutable("");
public static RemoteObject _tipocontrolfiltro_checkbox = RemoteObject.createImmutable("");
public static RemoteObject _tipocontrolfiltro_textfieldbutton = RemoteObject.createImmutable("");
public static RemoteObject _cargandodatos = RemoteObject.createImmutable(false);
public static RemoteObject _btncargarlistacamposquerysql = RemoteObject.declareNull("anywheresoftware.b4j.objects.ButtonWrapper");
public static RemoteObject _btncampostotext = RemoteObject.declareNull("anywheresoftware.b4j.objects.ButtonWrapper");
public static RemoteObject _btntexttocampos = RemoteObject.declareNull("anywheresoftware.b4j.objects.ButtonWrapper");
public static RemoteObject _lbltitlecampo = RemoteObject.declareNull("anywheresoftware.b4j.objects.LabelWrapper");
public static RemoteObject _lbltitleencabezado = RemoteObject.declareNull("anywheresoftware.b4j.objects.LabelWrapper");
public static RemoteObject _lbltitletipodato = RemoteObject.declareNull("anywheresoftware.b4j.objects.LabelWrapper");
public static RemoteObject _lblinfo = RemoteObject.declareNull("anywheresoftware.b4j.objects.LabelWrapper");
public static RemoteObject _colactualclv = RemoteObject.createImmutable(0);
public static RemoteObject _col1 = RemoteObject.createImmutable(0);
public static RemoteObject _col2 = RemoteObject.createImmutable(0);
public static RemoteObject _prefdialog = RemoteObject.declareNull("b4j.docU.preferencesdialog");
public static RemoteObject _txtipjrdc = RemoteObject.declareNull("anywheresoftware.b4j.objects.TextInputControlWrapper.TextFieldWrapper");
public static RemoteObject _txtpuertojrdc = RemoteObject.declareNull("anywheresoftware.b4j.objects.TextInputControlWrapper.TextFieldWrapper");
public static RemoteObject _txtcomandojrdc = RemoteObject.declareNull("anywheresoftware.b4j.objects.TextInputControlWrapper.TextFieldWrapper");
public static RemoteObject _txtparametrosjrdc = RemoteObject.declareNull("anywheresoftware.b4j.objects.TextInputControlWrapper.TextFieldWrapper");
public static RemoteObject _txttipoorigendatos = RemoteObject.declareNull("anywheresoftware.b4j.objects.TextInputControlWrapper.TextFieldWrapper");
public static RemoteObject _pnlorigensql = RemoteObject.declareNull("anywheresoftware.b4j.objects.PaneWrapper.ConcretePaneWrapper");
public static RemoteObject _lbltitletipoorigendatos = RemoteObject.declareNull("anywheresoftware.b4j.objects.LabelWrapper");
public static RemoteObject _lbltitleipjrdc = RemoteObject.declareNull("anywheresoftware.b4j.objects.LabelWrapper");
public static RemoteObject _lbltitlepuertojrdc = RemoteObject.declareNull("anywheresoftware.b4j.objects.LabelWrapper");
public static RemoteObject _lbltitlecomandojrdc = RemoteObject.declareNull("anywheresoftware.b4j.objects.LabelWrapper");
public static RemoteObject _lbltitleparametrosjrdc = RemoteObject.declareNull("anywheresoftware.b4j.objects.LabelWrapper");
public static RemoteObject _datosorigendatos = RemoteObject.declareNull("b4j.docU.jamtableviewcamposbuilder._tipoorigendatos");
public static RemoteObject _fechaultimamodificacion = RemoteObject.createImmutable(0L);
public static RemoteObject _btneditarorigenjrdc = RemoteObject.declareNull("anywheresoftware.b4j.objects.ButtonWrapper");
public static RemoteObject _lstprimarykey = RemoteObject.declareNull("anywheresoftware.b4a.objects.collections.List");
public static RemoteObject _corrigiendochkboxesfecha = RemoteObject.createImmutable(false);
public static RemoteObject _corrigiendochkboxkeyid = RemoteObject.createImmutable(false);
public static RemoteObject _corrigiendochkboxesbooleano = RemoteObject.createImmutable(false);
public static RemoteObject _btnvaloresestilodefecto = RemoteObject.declareNull("anywheresoftware.b4j.objects.ButtonWrapper");
public static RemoteObject _btnvaloresestilodefectotodos = RemoteObject.declareNull("anywheresoftware.b4j.objects.ButtonWrapper");
public static RemoteObject _lblcolorfondoencabezados = RemoteObject.declareNull("anywheresoftware.b4a.objects.B4XViewWrapper");
public static RemoteObject _lblcolortextoencabezados = RemoteObject.declareNull("anywheresoftware.b4a.objects.B4XViewWrapper");
public static RemoteObject _txtrgbcolorfondoencabezados = RemoteObject.declareNull("anywheresoftware.b4a.objects.B4XViewWrapper");
public static RemoteObject _txtrgbcolortextoencabezados = RemoteObject.declareNull("anywheresoftware.b4a.objects.B4XViewWrapper");
public static RemoteObject _lblresetcolorfondoencabezados = RemoteObject.declareNull("anywheresoftware.b4a.objects.B4XViewWrapper");
public static RemoteObject _lblresetcolortextoencabezados = RemoteObject.declareNull("anywheresoftware.b4a.objects.B4XViewWrapper");
public static RemoteObject _lblcolorfondopanelinfo = RemoteObject.declareNull("anywheresoftware.b4a.objects.B4XViewWrapper");
public static RemoteObject _lblcolortextopanelinfo = RemoteObject.declareNull("anywheresoftware.b4a.objects.B4XViewWrapper");
public static RemoteObject _txtrgbcolorfondopanelinfo = RemoteObject.declareNull("anywheresoftware.b4a.objects.B4XViewWrapper");
public static RemoteObject _lblresetcolorfondopanelinfo = RemoteObject.declareNull("anywheresoftware.b4a.objects.B4XViewWrapper");
public static RemoteObject _txtrgbcolortextopanelinfo = RemoteObject.declareNull("anywheresoftware.b4a.objects.B4XViewWrapper");
public static RemoteObject _lblresetcolortextopanelinfo = RemoteObject.declareNull("anywheresoftware.b4a.objects.B4XViewWrapper");
public static RemoteObject _lblcolorfondofilasimpares = RemoteObject.declareNull("anywheresoftware.b4a.objects.B4XViewWrapper");
public static RemoteObject _lblcolorfondofilaspares = RemoteObject.declareNull("anywheresoftware.b4a.objects.B4XViewWrapper");
public static RemoteObject _txtrgbcolorfondofilasimpares = RemoteObject.declareNull("anywheresoftware.b4a.objects.B4XViewWrapper");
public static RemoteObject _txtrgbcolorfondofilaspares = RemoteObject.declareNull("anywheresoftware.b4a.objects.B4XViewWrapper");
public static RemoteObject _resetcolorfondofilasimpares = RemoteObject.declareNull("anywheresoftware.b4j.objects.LabelWrapper");
public static RemoteObject _lblresetcolorfondofilaspares = RemoteObject.declareNull("anywheresoftware.b4j.objects.LabelWrapper");
public static RemoteObject _b4xplusminusanchobordeitems = RemoteObject.declareNull("b4j.docU.b4xplusminus");
public static RemoteObject _lblcolorbordeitems = RemoteObject.declareNull("anywheresoftware.b4a.objects.B4XViewWrapper");
public static RemoteObject _txtrgbcolorbordeitems = RemoteObject.declareNull("anywheresoftware.b4j.objects.TextInputControlWrapper.TextFieldWrapper");
public static RemoteObject _lblresetcolorbordeitems = RemoteObject.declareNull("anywheresoftware.b4a.objects.B4XViewWrapper");
public static RemoteObject _bccolorpickerjamtableview = RemoteObject.declareNull("b4j.docU.bccolorpicker");
public static RemoteObject _lblcolorfondoencabezadocolumna = RemoteObject.declareNull("anywheresoftware.b4a.objects.B4XViewWrapper");
public static RemoteObject _txtrgbcolorfondoencabezadocolumna = RemoteObject.declareNull("anywheresoftware.b4a.objects.B4XViewWrapper");
public static RemoteObject _lblresetcolorfondoencabezadocolumna = RemoteObject.declareNull("anywheresoftware.b4a.objects.B4XViewWrapper");
public static RemoteObject _lblcolortextoencabezadocolumna = RemoteObject.declareNull("anywheresoftware.b4a.objects.B4XViewWrapper");
public static RemoteObject _txtrgbcolortextoencabezadocolumna = RemoteObject.declareNull("anywheresoftware.b4a.objects.B4XViewWrapper");
public static RemoteObject _lblresetcolortextoencabezadocolumna = RemoteObject.declareNull("anywheresoftware.b4a.objects.B4XViewWrapper");
public static RemoteObject _btnbuscaraliascampo = RemoteObject.declareNull("anywheresoftware.b4a.objects.B4XViewWrapper");
public static RemoteObject _mmodosnap = RemoteObject.createImmutable(false);
public static RemoteObject _offsetanterior = RemoteObject.createImmutable(0);
public static RemoteObject _primerpanelvisibleanterior = RemoteObject.createImmutable(0);
public static RemoteObject _scrollingdown = RemoteObject.createImmutable(false);
public static RemoteObject _cssutils = RemoteObject.declareNull("b4j.example.cssutils");
public static RemoteObject _dateutils = RemoteObject.declareNull("b4j.example.dateutils");
public static b4j.docU.main _main = null;
public static b4j.docU.mainmenu2 _mainmenu2 = null;
public static b4j.docU.utilidades _utilidades = null;
public static b4j.docU.cmauxcorreosexpress _cmauxcorreosexpress = null;
public static b4j.docU.cmauxtxt _cmauxtxt = null;
public static b4j.docU.jrdcquery _jrdcquery = null;
public static b4j.docU.dbutils _dbutils = null;
public static b4j.docU.transfermode _transfermode = null;
public static b4j.docU.jamrecordformbuilder _jamrecordformbuilder = null;
public static b4j.docU.b4xcollections _b4xcollections = null;
public static b4j.docU.jamlinknavision _jamlinknavision = null;
public static b4j.docU.cmpermisos _cmpermisos = null;
public static b4j.docU.jamtableviewcamposbuilder _jamtableviewcamposbuilder = null;
public static b4j.docU.httputils2service _httputils2service = null;
public static b4j.docU.xuiviewsutils _xuiviewsutils = null;
public static Object[] GetGlobals(RemoteObject _ref) throws Exception {
		return new Object[] {"B4XPlusMinusAnchoBordeItems",_ref.getField(false, "_b4xplusminusanchobordeitems"),"BCColorPickerjamTableView",_ref.getField(false, "_bccolorpickerjamtableview"),"btnBuscarAliasCampo",_ref.getField(false, "_btnbuscaraliascampo"),"btnCamposToText",_ref.getField(false, "_btncampostotext"),"btnCargarListaCamposQuerySQL",_ref.getField(false, "_btncargarlistacamposquerysql"),"btnEditarOrigenJRDC",_ref.getField(false, "_btneditarorigenjrdc"),"btnTextToCampos",_ref.getField(false, "_btntexttocampos"),"btnValoresEstiloDefecto",_ref.getField(false, "_btnvaloresestilodefecto"),"btnValoresEstiloDefectoTodos",_ref.getField(false, "_btnvaloresestilodefectotodos"),"CargandoDatos",_ref.getField(false, "_cargandodatos"),"cboCampo",_ref.getField(false, "_cbocampo"),"cboTipoControlFiltro",_ref.getField(false, "_cbotipocontrolfiltro"),"cboTipoDato",_ref.getField(false, "_cbotipodato"),"chkBoxCampoCalculado",_ref.getField(false, "_chkboxcampocalculado"),"chkBoxConValorDefecto",_ref.getField(false, "_chkboxconvalordefecto"),"chkBoxEsBooleano",_ref.getField(false, "_chkboxesbooleano"),"chkBoxEsFecha",_ref.getField(false, "_chkboxesfecha"),"chkboxKeyID",_ref.getField(false, "_chkboxkeyid"),"chkBoxNoNulo",_ref.getField(false, "_chkboxnonulo"),"clvListaCampos",_ref.getField(false, "_clvlistacampos"),"cmbTheme",_ref.getField(false, "_cmbtheme"),"Col1",_ref.getField(false, "_col1"),"Col2",_ref.getField(false, "_col2"),"ColActualCLV",_ref.getField(false, "_colactualclv"),"CorrigiendoChkBoxEsBooleano",_ref.getField(false, "_corrigiendochkboxesbooleano"),"CorrigiendoChkBoxEsFecha",_ref.getField(false, "_corrigiendochkboxesfecha"),"CorrigiendoChkBoxKeyID",_ref.getField(false, "_corrigiendochkboxkeyid"),"CSSUtils",_ref.getField(false, "_cssutils"),"CurrentFile",_ref.getField(false, "_currentfile"),"CurrentFileString",_ref.getField(false, "_currentfilestring"),"DateUtils",_ref.getField(false, "_dateutils"),"DatosOrigenDatos",_ref.getField(false, "_datosorigendatos"),"Dialog",_ref.getField(false, "_dialog"),"dragger",_ref.getField(false, "_dragger"),"FechaUltimaModificacion",_ref.getField(false, "_fechaultimamodificacion"),"FileChooser",_ref.getField(false, "_filechooser"),"frm",_ref.getField(false, "_frm"),"fx",_ref.getField(false, "_fx"),"lblColorBordeItems",_ref.getField(false, "_lblcolorbordeitems"),"lblColorFondoEncabezadoColumna",_ref.getField(false, "_lblcolorfondoencabezadocolumna"),"lblColorFondoEncabezados",_ref.getField(false, "_lblcolorfondoencabezados"),"lblColorFondoFilasImpares",_ref.getField(false, "_lblcolorfondofilasimpares"),"lblColorFondoFilasPares",_ref.getField(false, "_lblcolorfondofilaspares"),"lblColorFondoPanelInfo",_ref.getField(false, "_lblcolorfondopanelinfo"),"lblColorTextoEncabezadoColumna",_ref.getField(false, "_lblcolortextoencabezadocolumna"),"lblColorTextoEncabezados",_ref.getField(false, "_lblcolortextoencabezados"),"lblColorTextoPanelInfo",_ref.getField(false, "_lblcolortextopanelinfo"),"lblInfo",_ref.getField(false, "_lblinfo"),"lblOrdenKeyID",_ref.getField(false, "_lblordenkeyid"),"lblResetColorBordeItems",_ref.getField(false, "_lblresetcolorbordeitems"),"lblResetColorFondoEncabezadoColumna",_ref.getField(false, "_lblresetcolorfondoencabezadocolumna"),"lblResetColorFondoEncabezados",_ref.getField(false, "_lblresetcolorfondoencabezados"),"lblResetColorFondoFilasPares",_ref.getField(false, "_lblresetcolorfondofilaspares"),"lblResetColorFondoPanelInfo",_ref.getField(false, "_lblresetcolorfondopanelinfo"),"lblResetColorTextoEncabezadoColumna",_ref.getField(false, "_lblresetcolortextoencabezadocolumna"),"lblResetColorTextoEncabezados",_ref.getField(false, "_lblresetcolortextoencabezados"),"lblResetColorTextoPanelInfo",_ref.getField(false, "_lblresetcolortextopanelinfo"),"lblTitleCampo",_ref.getField(false, "_lbltitlecampo"),"lblTitleComandoJRDC",_ref.getField(false, "_lbltitlecomandojrdc"),"lblTitleEncabezado",_ref.getField(false, "_lbltitleencabezado"),"lblTitleIpJRDC",_ref.getField(false, "_lbltitleipjrdc"),"lblTitleParametrosJRDC",_ref.getField(false, "_lbltitleparametrosjrdc"),"lblTitlePuertoJRDC",_ref.getField(false, "_lbltitlepuertojrdc"),"lblTitleTipoDato",_ref.getField(false, "_lbltitletipodato"),"lblTitleTipoOrigenDatos",_ref.getField(false, "_lbltitletipoorigendatos"),"lstPrimaryKey",_ref.getField(false, "_lstprimarykey"),"MenuBar1",_ref.getField(false, "_menubar1"),"mModoSnap",_ref.getField(false, "_mmodosnap"),"OffsetAnterior",_ref.getField(false, "_offsetanterior"),"pnlOrigenSQL",_ref.getField(false, "_pnlorigensql"),"prefDialog",_ref.getField(false, "_prefdialog"),"PrimerPanelVisibleAnterior",_ref.getField(false, "_primerpanelvisibleanterior"),"ResetColorFondoFilasImpares",_ref.getField(false, "_resetcolorfondofilasimpares"),"ScrollingDown",_ref.getField(false, "_scrollingdown"),"TipoControlFiltro_CheckBox",_ref.getField(false, "_tipocontrolfiltro_checkbox"),"TipoControlFiltro_ComboBox",_ref.getField(false, "_tipocontrolfiltro_combobox"),"TipoControlFiltro_TextField",_ref.getField(false, "_tipocontrolfiltro_textfield"),"TipoControlFiltro_TextFieldButton",_ref.getField(false, "_tipocontrolfiltro_textfieldbutton"),"txtAliasCampo",_ref.getField(false, "_txtaliascampo"),"txtComandoJRDC",_ref.getField(false, "_txtcomandojrdc"),"txtID",_ref.getField(false, "_txtid"),"txtIpJRDC",_ref.getField(false, "_txtipjrdc"),"txtParametrosJRDC",_ref.getField(false, "_txtparametrosjrdc"),"txtPuertoJRDC",_ref.getField(false, "_txtpuertojrdc"),"txtRGBColorBordeItems",_ref.getField(false, "_txtrgbcolorbordeitems"),"txtRGBColorFondoEncabezadoColumna",_ref.getField(false, "_txtrgbcolorfondoencabezadocolumna"),"txtRGBColorFondoEncabezados",_ref.getField(false, "_txtrgbcolorfondoencabezados"),"txtRGBColorFondoFilasImpares",_ref.getField(false, "_txtrgbcolorfondofilasimpares"),"txtRGBColorFondoFilasPares",_ref.getField(false, "_txtrgbcolorfondofilaspares"),"txtRGBColorFondoPanelInfo",_ref.getField(false, "_txtrgbcolorfondopanelinfo"),"txtRGBColorTextoEncabezadoColumna",_ref.getField(false, "_txtrgbcolortextoencabezadocolumna"),"txtRGBColorTextoEncabezados",_ref.getField(false, "_txtrgbcolortextoencabezados"),"txtRGBColorTextoPanelInfo",_ref.getField(false, "_txtrgbcolortextopanelinfo"),"txtTipoOrigenDatos",_ref.getField(false, "_txttipoorigendatos"),"txtValorDefecto",_ref.getField(false, "_txtvalordefecto"),"txtValorTrueCampoBooleano",_ref.getField(false, "_txtvalortruecampobooleano"),"version",_ref.getField(false, "_version"),"xui",_ref.getField(false, "_xui")};
}
}